INSERT INTO person(firstName, pin, registrationDate) VALUES ('Bolek', '1234', '2012-01-10')
INSERT INTO person(firstName, pin, registrationDate) VALUES ('Lolek', '1235', '2012-01-10')
INSERT INTO person(firstName, pin, registrationDate) VALUES ('Tola', '1236', '2012-01-10')

INSERT INTO car(make, model, sold) VALUES ('Fiat', 'Bravo', false)
INSERT INTO car(make, model, sold) VALUES ('Ford', 'Mondeo', false)
INSERT INTO car(make, model, sold) VALUES ('Ford', 'Focus', false)
INSERT INTO car(make, model, sold) VALUES ('Opel', 'Vectra', false)
INSERT INTO car(make, model, sold) VALUES ('Opel', 'Astra', false)
INSERT INTO car(make, model, sold) VALUES ('Renault', 'Megane', false)